apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network-sec
commonLabels:
  app.kubernetes.io/part-of: network-sec

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - mysql.yaml
  - mongodb.yaml
  - kafka.yaml
  - redis.yaml
  - warrior.yaml
  - weapon.yaml
  - enemy.yaml
  - dragon.yaml
  - coin.yaml
  - battle.yaml
  - battlespell.yaml
  - arena.yaml
  - heal.yaml
  - repair.yaml
  - gateway.yaml


