apiVersion: v1
kind: Secret
metadata:
  name: network-sec-shared-secrets
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME_WARRIOR: warrior_db
  DB_NAME_COIN: coin_db
  DB_NAME_REPAIR: repair_db
  DB_NAME_HEAL: heal_db
  DB_NAME_ARENA: arena_db
  DB_NAME_BATTLE: battle_db
  MYSQL_DB_NAME: coin_db
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  MONGODB_URI: mongodb://mongodb:27017
  KAFKA_BROKERS: kafka:9092
  REDIS_ADDR: redis:6379
  REDIS_PASSWORD: ""
  REDIS_DB: "0"
  JWT_SECRET: change-me
  GIN_MODE: release

